### ISSUE TITLE
Kicking bot = NPE

### ISSUE THREAD

**Issue by sponges** [sponges/dabBot#7]

**Comment by sponges** [comment]
```
[20:42:41] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[20:42:41] [Fatal] [JDA]: Encountered an exception:
[20:42:41] [Fatal] [JDA]: java.lang.NullPointerException
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.openAudioConnection(AudioManagerImpl.java:83)
	at ovh.not.javamusicbot.GuildMusicManager.open(GuildMusicManager.java:33)
	at ovh.not.javamusicbot.command.PlayCommand.on(PlayCommand.java:45)
	at ovh.not.javamusicbot.Listener.onMessageReceived(Listener.java:55)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:319)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:125)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:47)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:688)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:437)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:262)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:240)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:965)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:748)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)
```

GuildMusicManager.java:33
```java
guild.getAudioManager().openAudioConnection(channel);
```

**Comment by sponges** [comment]
"fix" is a very loose term. I forked jda removed some code and implemented it in mine. https://github.com/sponges/JDA
